"""
Init + guided onboarding for humans and AI agents.

Agents should:
  1. Run `python -m material_price_audit init`
  2. Read printed AGENT_GUIDE / data/output/AGENT_NEXT.md
  3. Ask user the listed questions, then run next_command
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from . import __version__
from .env_check import check_environment
from .platforms import BUILTIN, resolve_enabled_platforms


# 不再预填全站；必须用户 select-platforms / --platforms / 网页勾选
DEFAULT_PLATFORMS: list[str] = []


@dataclass
class ProjectState:
    root: str
    version: str
    env_ok: bool
    env_errors: list[str] = field(default_factory=list)
    env_hints: list[str] = field(default_factory=list)
    config_path: str = ""
    config_exists: bool = False
    input_path: str = ""
    input_exists: bool = False
    output_dir: str = ""
    profile_dir: str = ""
    platforms_enabled: list[str] = field(default_factory=list)
    phase: str = "unknown"  # init | need_env | need_inquiry | need_platforms | need_login | ready_scrape | done
    next_action: str = ""
    next_command: str = ""
    questions_for_user: list[str] = field(default_factory=list)
    user_checklist: list[str] = field(default_factory=list)


def package_root() -> Path:
    return Path(__file__).resolve().parents[1]


def write_config(
    path: Path,
    platforms: list[str],
    tax_divisor: float = 1.13,
    extra_definitions: dict | None = None,
) -> None:
    plats = list(platforms) if platforms is not None else list(DEFAULT_PLATFORMS)
    lines = [
        f"# generated by material-price-audit init @ {datetime.now().isoformat(timespec='seconds')}",
        f"# version {__version__}",
        "# platforms.enabled 只写用户选过的站；空=尚未选择",
        "",
        "pricing:",
        f"  tax_divisor: {tax_divisor}",
        "  never_exceed_submit: true",
        "  open_detail: true",
        "  min_title_score: 1",
        "  platform_strategy: waterfall",
        "",
        "browser:",
        "  channel: chrome",
        "  headless: false",
        "  login_wait_seconds: 120",
        "  page_timeout_ms: 60000",
        "  between_items_sleep: 1.2",
        "",
        "platforms:",
        "  enabled:",
    ]
    if not plats:
        lines.append("    # 空：请先 select-platforms 或 --platforms guangcai,jd")
    for p in plats:
        # quote numeric-looking ids so YAML keeps them as strings (e.g. "1688")
        if str(p).isdigit():
            lines.append(f'    - "{p}"')
        else:
            lines.append(f"    - {p}")
    lines.append("  definitions: {}")
    if extra_definitions:
        # simple yaml dump without dependency on nested complexity
        lines.append("  # custom definitions were requested; edit below as needed")
    lines += [
        "",
        "excel:",
        "  submit_price_headers: [报送不含税单价, 报送单价, 投标单价]",
        "  audit_price_headers: [审定不含税单价, 审定单价]",
        "  name_headers: [材料名称, 名称, 设备名称]",
        "  spec_headers: [规格、型号, 规格型号, 规格, 型号]",
        "  unit_headers: [单位]",
        "  qty_headers: [数量]",
        "  brand_headers: [产地、品牌及特殊要求, 品牌, 产地品牌]",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def detect_state(root: Path | None = None) -> ProjectState:
    root = root or package_root()
    env = check_environment(require_browser=False, use_cache=True)
    cfg_path = root / "config.yaml"
    input_dir = root / "data" / "input"
    # smart detect any excel in input dir
    try:
        from .excel_io import resolve_inquiry_path

        input_path = resolve_inquiry_path(None, default_dir=input_dir)
        input_exists = True
    except Exception:
        input_path = input_dir
        input_exists = False
    output_dir = root / "data" / "output"
    profile = root / ".browser-profile"

    platforms: list[str] = []
    selected = output_dir / "platforms.selected"
    if selected.exists():
        raw = selected.read_text(encoding="utf-8")
        platforms = [
            p.strip()
            for line in raw.replace(",", "\n").splitlines()
            for p in [line.strip()]
            if p and not p.startswith("#")
        ]
    elif cfg_path.exists():
        try:
            import yaml

            cfg = yaml.safe_load(cfg_path.read_text(encoding="utf-8")) or {}
            platforms = resolve_enabled_platforms(cfg, None)
        except Exception:
            platforms = []

    st = ProjectState(
        root=str(root),
        version=__version__,
        env_ok=env.ok,
        env_errors=list(env.errors),
        env_hints=list(env.hints),
        config_path=str(cfg_path),
        config_exists=cfg_path.exists(),
        input_path=str(input_path),
        input_exists=input_exists,
        output_dir=str(output_dir),
        profile_dir=str(profile),
        platforms_enabled=platforms,
    )

    # phase machine
    if not env.ok:
        st.phase = "need_env"
        st.next_action = "Install missing dependencies, then re-run init/check"
        st.next_command = "python -m material_price_audit check"
        st.questions_for_user = [
            "是否允许我执行 pip install -r requirements.txt 与 playwright install chromium？",
        ]
        st.user_checklist = env.hints
        return st

    if not cfg_path.exists():
        st.phase = "need_config"
        st.next_action = "Run init to create config.yaml and folders"
        st.next_command = "python -m material_price_audit init"
        st.questions_for_user = [
            "你要启用哪些报价平台？（如 jd,1688,zkh,taobao；可自定义网站）",
            "含税转不含税除数是否用 1.13？",
        ]
        return st

    if not input_exists:
        st.phase = "need_inquiry"
        st.next_action = "User must place any inquiry Excel under data/input/ (any filename)"
        st.next_command = (
            "python -m material_price_audit status "
            "--output data/output/result.xlsx "
            "--evidence data/output/evidence.json"
        )
        st.questions_for_user = [
            "请把询价 Excel（任意文件名，如「安装专业询价材料设备.xlsx」）放到 data/input/，表头需含「报送不含税单价」。放好即可继续。",
        ]
        st.user_checklist = [
            f"把询价 .xlsx 放入: {input_dir}（不必改名 inquiry.xlsx，工具会自动识别）",
            "确认表头有: 材料名称 / 规格型号 / 报送不含税单价",
        ]
        return st

    if not platforms:
        st.phase = "need_platforms"
        st.next_action = "User must pick platforms; never auto-login all sites"
        st.next_command = "python -m material_price_audit select-platforms"
        st.questions_for_user = [
            "要比价哪些网站？例如只要广材+京东：回 guangcai,jd",
            "或运行 select-platforms 终端勾选 / 打开 docs/platform-select.html",
        ]
        st.user_checklist = [
            "只勾选有账号、要查的站",
            "未勾选的站不会打开登录页",
        ]
        return st

    # has config + input + platforms
    st.phase = "need_login"
    st.next_action = "Login ONLY selected platforms, then smoke scrape --limit 8"
    st.next_command = (
        f"python -m material_price_audit login --profile .browser-profile "
        f"--platforms {','.join(platforms)}"
    )
    st.questions_for_user = [
        f"将只登录这些平台：{', '.join(platforms)}。开始吗？（改平台先 select-platforms）",
        "登录完成后回复「登录完成」，试跑 scrape --limit 8。",
    ]
    st.user_checklist = [
        "仅在已选平台登录",
        "试跑后打开 data/output/result.xlsx →「实抓汇总」",
    ]

    # if evidence exists with verified, suggest full scrape or rfq
    evidence = root / "data" / "output" / "evidence.json"
    if evidence.exists():
        try:
            data = json.loads(evidence.read_text(encoding="utf-8"))
            n = sum(1 for e in data.get("results", []) if e.get("status") == "verified")
            if n > 0:
                st.phase = "ready_scrape"
                st.next_action = f"Already have {n} verified rows; offer full scrape or rfq"
                st.next_command = (
                    f"python -m material_price_audit scrape "
                    f"--output data/output/result.xlsx "
                    f"--evidence data/output/evidence.json "
                    f"--profile .browser-profile "
                    f"--platforms {','.join(platforms)}"
                )
                st.questions_for_user = [
                    f"已有 {n} 条 verified 证据。继续全量 scrape，还是先导出 rfq？",
                ]
        except Exception:
            pass

    return st


def run_init(
    root: Path | None = None,
    platforms: list[str] | None = None,
    tax_divisor: float = 1.13,
    force_config: bool = False,
) -> ProjectState:
    root = root or package_root()
    (root / "data" / "input").mkdir(parents=True, exist_ok=True)
    (root / "data" / "output").mkdir(parents=True, exist_ok=True)
    (root / ".browser-profile").mkdir(parents=True, exist_ok=True)

    cfg_path = root / "config.yaml"
    example = root / "config.example.yaml"
    # None = 不改平台列表；[] = 明确清空；有内容 = 写入用户选择
    if platforms is None:
        plats = list(DEFAULT_PLATFORMS)
        rewrite_plats = False
    else:
        plats = list(platforms)
        rewrite_plats = True
    known = set(BUILTIN.keys())
    for p in plats:
        if p not in known:
            pass

    if force_config or not cfg_path.exists():
        write_config(cfg_path, plats, tax_divisor=tax_divisor)
    elif rewrite_plats:
        write_config(cfg_path, plats, tax_divisor=tax_divisor)

    # copy example if missing
    if not example.exists():
        # leave as is
        pass

    st = detect_state(root)
    # after init, always write guide files
    write_agent_guide(root, st)
    return st


def write_agent_guide(root: Path, st: ProjectState) -> Path:
    out_dir = root / "data" / "output"
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / "AGENT_NEXT.md"
    json_path = out_dir / "agent_state.json"

    json_path.write_text(
        json.dumps(asdict(st), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    md = f"""# AGENT_NEXT — 给 AI Agent 的下一步指令

> 自动生成于 {datetime.now().isoformat(timespec='seconds')} · tool v{st.version}

## 当前阶段 phase

`{st.phase}`

## 项目路径

- root: `{st.root}`
- config: `{st.config_path}` (exists={st.config_exists})
- input: `{st.input_path}` (exists={st.input_exists})
- output_dir: `{st.output_dir}`
- profile: `{st.profile_dir}`
- platforms: `{', '.join(st.platforms_enabled)}`
- env_ok: `{st.env_ok}`

## 你必须遵守

1. 无 verified 证据不得填写审定单价
2. 路径必须显式：`--input --output --evidence --profile`
3. 平台由用户指定，不要写死只有京东/阿里
4. 先试跑 `--limit 8`，成功再全量
5. 登录必须用户在浏览器完成

## next_action

{st.next_action}

## next_command

```bash
cd "{st.root}"
{st.next_command}
```

## 请向用户提问（逐条问，不要一次抛完）

"""
    for i, q in enumerate(st.questions_for_user, 1):
        md += f"{i}. {q}\n"

    if st.env_errors:
        md += "\n## 环境错误\n\n"
        for e in st.env_errors:
            md += f"- {e}\n"
        md += "\n安装提示:\n"
        for h in st.env_hints:
            md += f"- `{h}`\n"

    md += """
## 完整阶段机（phase machine）

| phase | 含义 | Agent 动作 |
|-------|------|------------|
| need_env | 缺依赖 | 引导安装 playwright/openpyxl，再 check |
| need_config | 无 config | 运行 init，问平台列表 |
| need_inquiry | 无询价单 | 让用户把任意文件名 Excel 放到 data/input/ |
| need_login | 可登录 | login --platforms ...，用户浏览器登录 |
| ready_scrape | 可抓取 | scrape --limit 8 → 全量 → rfq |
| done | 完成 | 汇报路径与命中数 |

## 用户 checklist

"""
    for c in st.user_checklist:
        md += f"- [ ] {c}\n"

    md += f"""
## 标准路径约定

| 用途 | 路径 |
|------|------|
| 入参询价单 | `data/input/*.xlsx`（任意文件名，自动识别含「报送不含税单价」的表） |
| 出参结果 | `data/output/result.xlsx` |
| 出参证据 | `data/output/evidence.json` |
| 出参 RFQ | `data/output/rfq.xlsx` |
| Agent 状态 | `data/output/agent_state.json` |
| Agent 下一步 | `data/output/AGENT_NEXT.md` |

## 对用户说的开场白（可直接用）

你好。我来帮你做「材料询价核价」初始化。

1. 先检查电脑是否装好 Playwright  
2. 请你选择要登录/比价的网站（广材 / 慧讯 iccchina / 领材 hylcw / 京东…）  
3. 把询价单丢进 data/input/（文件名随意）  
4. 你在浏览器登录各平台后，我再自动试跑 8 条给你核对  

当前阶段：**{st.phase}**  
当前启用平台：**{', '.join(st.platforms_enabled) or '（未配置）'}**
"""
    md_path.write_text(md, encoding="utf-8")
    return md_path


def print_agent_block(st: ProjectState, guide_path: Path | None = None) -> None:
    """Machine-friendly block for agents to parse from terminal."""
    print("")
    print("========== AGENT_GUIDE_BEGIN ==========")
    print(f"phase: {st.phase}")
    print(f"env_ok: {st.env_ok}")
    print(f"config_exists: {st.config_exists}")
    print(f"input_exists: {st.input_exists}")
    print(f"platforms: {','.join(st.platforms_enabled)}")
    print(f"next_action: {st.next_action}")
    print(f"next_command: {st.next_command}")
    print("questions:")
    for q in st.questions_for_user:
        print(f"  - {q}")
    if guide_path:
        print(f"guide_file: {guide_path}")
    print(f"state_file: {Path(st.output_dir) / 'agent_state.json'}")
    print("========== AGENT_GUIDE_END ==========")
    print("")
    print("【请对用户说】")
    if st.phase == "need_env":
        print("环境还没就绪。需要先安装 Python 依赖和 Playwright 浏览器。")
        for h in st.env_hints:
            print(f"  请执行: {h}")
    elif st.phase in ("need_config",) or not st.config_exists:
        print("已准备好项目文件夹。请告诉我：要用哪些报价网站？例如：京东+1688+震坤行。")
    elif st.phase == "need_inquiry":
        print("请把询价 Excel 放到 data/input/ 目录（任意文件名，不必叫 inquiry.xlsx）：")
        print(f"  {Path(st.root) / 'data' / 'input'}")
        print("表里需要有「报送不含税单价」这一列；多个 xlsx 时会按表头自动选。")
    elif st.phase == "need_login":
        print(
            f"询价单已就绪。接下来请登录这些平台：{', '.join(st.platforms_enabled)}。"
            "我打开浏览器后，请你在窗口里登录，完成后回复「登录完成」。"
        )
    elif st.phase == "ready_scrape":
        print("已有部分抓取结果。可以继续全量抓取，或导出未命中材料的供应商询价单。")
    else:
        print(st.next_action)
